"""add timestamps mode sources

Revision ID: 45bf79c8461d
Revises: 02c4358a66fc
Create Date: 2026-06-17 11:34:35.747791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45bf79c8461d'
down_revision: Union[str, Sequence[str], None] = '02c4358a66fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('mode', sa.String(length=50), nullable=False))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column(
        'messages',
        sa.Column(
            'token_count',
            sa.Integer(),
            server_default='0',
            nullable=False
        )
    )

    op.add_column(
        'messages',
        sa.Column(
            'sources',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='[]',
            nullable=False
        )
    )
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'sources')
    op.drop_column('messages', 'token_count')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'mode')
    # ### end Alembic commands ###
